blank_issues_enabled: true
contact_links:
  - name: ðŸ—£ Subproject discussions 
    url: https://github.com/camaraproject/Commonalities/discussions
    about: Please ask and answer questions here.
  - name: ðŸ“– CAMARA API Design Guidelines
    url: https://github.com/camaraproject/Commonalities/documentation/API-design-guidelines.md
    about: Please refer to the design guidelines.
